# Generated by Django 5.1.4 on 2026-05-18 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('leave_request', 'Leave request'), ('document', 'Document approval'), ('education_claim', 'Education assistance claim'), ('onboarding', 'Onboarding task'), ('offboarding', 'Offboarding task'), ('salary_change', 'Salary change'), ('recruitment_offer', 'Recruitment offer'), ('payroll', 'Payroll approval'), ('hr_case', 'HR case'), ('general', 'General approval')], db_index=True, max_length=24)),
                ('is_default', models.BooleanField(default=False, help_text='Used when a domain object of this type needs a workflow.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Order within the workflow — lower decides first.')),
                ('approver_type', models.CharField(choices=[('role', 'Anyone holding a role'), ('named_user', 'A specific named user'), ('line_manager', "The subject's line manager"), ('department_head', "The subject's department head")], default='role', max_length=20)),
                ('sla_days', models.PositiveIntegerField(default=0, help_text='Days before the stage is escalated; 0 = no SLA.')),
                ('allow_request_info', models.BooleanField(default=True, help_text='Approver may send the item back for more info.')),
                ('approver_role', models.ForeignKey(blank=True, help_text="Required when approver type is 'role'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_stages', to='accounts.role')),
                ('approver_user', models.ForeignKey(blank=True, help_text="Required when approver type is 'named user'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_stages', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflow')),
            ],
            options={
                'ordering': ['workflow', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('subject', models.CharField(help_text='Human-readable label for the item.', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_review', 'Pending review'), ('pending_approval', 'Pending approval'), ('more_info', 'More information required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Snapshot data for notification rendering / display.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stage_entered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL)),
                ('subject_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflow')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('submit', 'Submitted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('request_info', 'Requested more information'), ('provide_info', 'Provided information'), ('comment', 'Commented'), ('escalate', 'Escalated'), ('cancel', 'Cancelled'), ('complete', 'Completed')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflowinstance')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['tenant', 'entity_type', 'is_active'], name='workflows_w_tenant__a0dd39_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_workflow_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='workflowstage',
            index=models.Index(fields=['tenant', 'workflow'], name='workflows_w_tenant__234020_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='uniq_workflowstage_sequence_per_workflow'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['tenant', 'status'], name='workflows_w_tenant__45fb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='workflows_w_tenant__a49202_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['tenant', 'current_stage', 'status'], name='workflows_w_tenant__10832b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['tenant', 'instance', 'created_at'], name='workflows_w_tenant__103c88_idx'),
        ),
    ]
