# Generated by Django 5.1.4 on 2026-05-18 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_key', models.CharField(choices=[('welcome', 'Welcome email'), ('password_reset', 'Password reset'), ('leave_submitted', 'Leave request submitted'), ('leave_stage_advanced', 'Leave advanced a stage'), ('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('leave_cancelled', 'Leave cancelled'), ('leave_pending_reminder', 'Leave awaiting approval'), ('leave_finance_notice', 'Leave finance notice'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('document_expiring', 'Document expiring'), ('document_missing', 'Missing required document'), ('birthday', 'Employee birthday'), ('contract_expiry', 'Contract expiry reminder'), ('probation_ending', 'Probation ending reminder'), ('retirement_reminder', 'Retirement approaching'), ('general', 'General notification')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('url', models.CharField(blank=True, help_text='Optional in-app link to the subject.', max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_key', models.CharField(blank=True, choices=[('welcome', 'Welcome email'), ('password_reset', 'Password reset'), ('leave_submitted', 'Leave request submitted'), ('leave_stage_advanced', 'Leave advanced a stage'), ('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('leave_cancelled', 'Leave cancelled'), ('leave_pending_reminder', 'Leave awaiting approval'), ('leave_finance_notice', 'Leave finance notice'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('document_expiring', 'Document expiring'), ('document_missing', 'Missing required document'), ('birthday', 'Employee birthday'), ('contract_expiry', 'Contract expiry reminder'), ('probation_ending', 'Probation ending reminder'), ('retirement_reminder', 'Retirement approaching'), ('general', 'General notification')], db_index=True, max_length=50)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_key', models.CharField(choices=[('welcome', 'Welcome email'), ('password_reset', 'Password reset'), ('leave_submitted', 'Leave request submitted'), ('leave_stage_advanced', 'Leave advanced a stage'), ('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('leave_cancelled', 'Leave cancelled'), ('leave_pending_reminder', 'Leave awaiting approval'), ('leave_finance_notice', 'Leave finance notice'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('document_expiring', 'Document expiring'), ('document_missing', 'Missing required document'), ('birthday', 'Employee birthday'), ('contract_expiry', 'Contract expiry reminder'), ('probation_ending', 'Probation ending reminder'), ('retirement_reminder', 'Retirement approaching'), ('general', 'General notification')], help_text='The event this template renders.', max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('channel', models.CharField(choices=[('email', 'Email only'), ('in_app', 'In-app only'), ('both', 'Email and in-app')], default='both', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_enabled', models.BooleanField(default=True, help_text='Disable to suppress this notification entirely.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed / matched'), ('unmatched', 'Unmatched'), ('failed', 'Processing failed')], db_index=True, default='received', max_length=12)),
                ('matched_entity_type', models.CharField(blank=True, max_length=80)),
                ('matched_entity_id', models.CharField(blank=True, max_length=64)),
                ('processing_note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='notificatio_tenant__b579e8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'recipient', 'is_read'], name='notificatio_tenant__89dcf7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'recipient', 'created_at'], name='notificatio_tenant__0df3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['tenant', 'status'], name='notificatio_tenant__16ab8d_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', 'attempts'], name='notificatio_status_713dff_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['tenant', 'event_key'], name='notificatio_tenant__5cd294_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_key'), name='uniq_notificationtemplate_event_per_tenant'),
        ),
    ]
