# Generated by Django 5.1.4 on 2026-05-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='event_key',
            field=models.CharField(blank=True, choices=[('welcome', 'Welcome email'), ('password_reset', 'Password reset'), ('leave_submitted', 'Leave request submitted'), ('leave_stage_advanced', 'Leave advanced a stage'), ('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('leave_cancelled', 'Leave cancelled'), ('leave_pending_reminder', 'Leave awaiting approval'), ('leave_finance_notice', 'Leave finance notice'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('document_expiring', 'Document expiring'), ('document_missing', 'Missing required document'), ('workflow_submitted', 'Workflow item awaiting you'), ('workflow_approved', 'Workflow item approved'), ('workflow_rejected', 'Workflow item rejected'), ('workflow_info_requested', 'Workflow needs more info'), ('workflow_escalated', 'Workflow item escalated'), ('workflow_completed', 'Workflow completed'), ('birthday', 'Employee birthday'), ('contract_expiry', 'Contract expiry reminder'), ('probation_ending', 'Probation ending reminder'), ('retirement_reminder', 'Retirement approaching'), ('general', 'General notification')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_key',
            field=models.CharField(choices=[('welcome', 'Welcome email'), ('password_reset', 'Password reset'), ('leave_submitted', 'Leave request submitted'), ('leave_stage_advanced', 'Leave advanced a stage'), ('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('leave_cancelled', 'Leave cancelled'), ('leave_pending_reminder', 'Leave awaiting approval'), ('leave_finance_notice', 'Leave finance notice'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('document_expiring', 'Document expiring'), ('document_missing', 'Missing required document'), ('workflow_submitted', 'Workflow item awaiting you'), ('workflow_approved', 'Workflow item approved'), ('workflow_rejected', 'Workflow item rejected'), ('workflow_info_requested', 'Workflow needs more info'), ('workflow_escalated', 'Workflow item escalated'), ('workflow_completed', 'Workflow completed'), ('birthday', 'Employee birthday'), ('contract_expiry', 'Contract expiry reminder'), ('probation_ending', 'Probation ending reminder'), ('retirement_reminder', 'Retirement approaching'), ('general', 'General notification')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_key',
            field=models.CharField(choices=[('welcome', 'Welcome email'), ('password_reset', 'Password reset'), ('leave_submitted', 'Leave request submitted'), ('leave_stage_advanced', 'Leave advanced a stage'), ('leave_approved', 'Leave approved'), ('leave_rejected', 'Leave rejected'), ('leave_cancelled', 'Leave cancelled'), ('leave_pending_reminder', 'Leave awaiting approval'), ('leave_finance_notice', 'Leave finance notice'), ('document_approved', 'Document approved'), ('document_rejected', 'Document rejected'), ('document_expiring', 'Document expiring'), ('document_missing', 'Missing required document'), ('workflow_submitted', 'Workflow item awaiting you'), ('workflow_approved', 'Workflow item approved'), ('workflow_rejected', 'Workflow item rejected'), ('workflow_info_requested', 'Workflow needs more info'), ('workflow_escalated', 'Workflow item escalated'), ('workflow_completed', 'Workflow completed'), ('birthday', 'Employee birthday'), ('contract_expiry', 'Contract expiry reminder'), ('probation_ending', 'Probation ending reminder'), ('retirement_reminder', 'Retirement approaching'), ('general', 'General notification')], help_text='The event this template renders.', max_length=50),
        ),
    ]
