# Generated by Django 5.1.4 on 2026-05-19 02:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_assistance', '0001_initial'),
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('health', 'Health / medical'), ('dental', 'Dental'), ('vision', 'Vision'), ('life_insurance', 'Life insurance'), ('disability', 'Disability cover'), ('pension', 'Pension / retirement'), ('wellness', 'Wellness'), ('transport', 'Transport'), ('housing', 'Housing'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=160)),
                ('contribution_basis', models.CharField(choices=[('fixed', 'Fixed amount per period'), ('percentage', 'Percentage of basic salary')], default='fixed', max_length=12)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount, or percentage of basic salary, per the basis.', max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount, or percentage of basic salary, per the basis.', max_digits=12)),
                ('is_taxable', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=True, help_text='Enrolments need HR approval before they activate.')),
                ('covers_dependants', models.BooleanField(default=False)),
                ('eligibility_min_months', models.PositiveSmallIntegerField(default=0, help_text='Months of service required before enrolling.')),
                ('eligible_employment_statuses', models.JSONField(blank=True, default=list, help_text='Employment statuses eligible to enrol (empty = all).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pay_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefit_types', to='payroll.paycomponent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('declined', 'Declined'), ('terminated', 'Terminated')], db_index=True, default='pending', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='benefits.benefittype')),
                ('covered_dependants', models.ManyToManyField(blank=True, related_name='benefit_enrolments', to='education_assistance.dependant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BenefitEnrolmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(choices=[('enrolled', 'Enrolled'), ('approved', 'Approved'), ('declined', 'Declined'), ('suspended', 'Suspended'), ('resumed', 'Resumed'), ('terminated', 'Terminated'), ('updated', 'Updated')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='benefits.employeebenefit')),
            ],
            options={
                'verbose_name_plural': 'Benefit enrolment history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='benefittype',
            index=models.Index(fields=['tenant', 'is_active'], name='benefits_be_tenant__d1e325_idx'),
        ),
        migrations.AddConstraint(
            model_name='benefittype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_benefittype_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='employeebenefit',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='benefits_em_tenant__e54aff_idx'),
        ),
        migrations.AddIndex(
            model_name='employeebenefit',
            index=models.Index(fields=['tenant', 'benefit_type', 'status'], name='benefits_em_tenant__55f16a_idx'),
        ),
        migrations.AddIndex(
            model_name='benefitenrolmenthistory',
            index=models.Index(fields=['tenant', 'enrolment', 'created_at'], name='benefits_be_tenant__0cfd11_idx'),
        ),
    ]
