# Generated by Django 5.1.4 on 2026-05-18 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_number', models.CharField(db_index=True, max_length=40)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('preferred_name', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], default='undisclosed', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee-photos/')),
                ('national_id', models.CharField(blank=True, max_length=60)),
                ('passport_number', models.CharField(blank=True, max_length=60)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('alternate_phone', models.CharField(blank=True, max_length=32)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Intern'), ('consultant', 'Consultant')], default='full_time', max_length=20)),
                ('employment_status', models.CharField(choices=[('probation', 'Probation'), ('active', 'Active'), ('on_leave', 'On leave'), ('suspended', 'Suspended'), ('notice', 'Serving notice'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('retired', 'Retired'), ('archived', 'Archived')], db_index=True, default='probation', max_length=20)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('retirement_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Actual exit/termination date.', null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=160)),
                ('bank_account_name', models.CharField(blank=True, max_length=160)),
                ('bank_account_number', models.CharField(blank=True, max_length=64)),
                ('bank_branch_code', models.CharField(blank=True, max_length=40)),
                ('tax_number', models.CharField(blank=True, max_length=60)),
                ('tax_code', models.CharField(blank=True, max_length=40)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salary_currency', models.CharField(default='GBP', max_length=3)),
                ('benefits_eligible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organisation.costcentre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organisation.department')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organisation.grade')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organisation.jobtitle')),
                ('line_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organisation.position')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('work_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organisation.location')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('relationship', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=32)),
                ('alternate_phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('hire', 'Hire'), ('position_change', 'Position change'), ('department_transfer', 'Department transfer'), ('salary_change', 'Salary change'), ('manager_change', 'Reporting line change'), ('status_change', 'Employment status change'), ('grade_change', 'Grade change'), ('contract_change', 'Contract change'), ('confirmation', 'Confirmation / probation passed'), ('exit', 'Exit / termination'), ('other', 'Other')], max_length=30)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('field_changed', models.CharField(blank=True, max_length=80)),
                ('previous_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('contract_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Intern'), ('consultant', 'Consultant')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='draft', max_length=20)),
                ('job_title', models.CharField(blank=True, help_text='Title snapshot at signing.', max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'employment_status'], name='employees_e_tenant__20ea29_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'department'], name='employees_e_tenant__f66b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'line_manager'], name='employees_e_tenant__aade58_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'contract_end_date'], name='employees_e_tenant__335edb_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'probation_end_date'], name='employees_e_tenant__b52460_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee_number'), name='uniq_employee_number_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['tenant', 'employee'], name='employees_e_tenant__72fd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeehistory',
            index=models.Index(fields=['tenant', 'employee', 'created_at'], name='employees_e_tenant__4b2f51_idx'),
        ),
        migrations.AddIndex(
            model_name='employeehistory',
            index=models.Index(fields=['tenant', 'change_type'], name='employees_e_tenant__8d4fee_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['tenant', 'employee'], name='employees_e_tenant__6a10c7_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['tenant', 'status'], name='employees_e_tenant__185e94_idx'),
        ),
    ]
