# Generated by Django 5.1.4 on 2026-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_contracttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='discovered_placeholders',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
