# Generated by Django 5.1.4 on 2026-05-18 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('report_key', models.CharField(choices=[('employee_list', 'Employee list'), ('headcount_by_department', 'Headcount by department'), ('new_hires', 'New hires'), ('exits', 'Exits'), ('contract_expiry', 'Contract expiry'), ('probation_ending', 'Probation ending'), ('retirement_approaching', 'Retirement approaching'), ('leave_balances', 'Leave balances'), ('leave_taken', 'Leave taken'), ('leave_trends', 'Leave trends'), ('missing_documents', 'Missing required documents'), ('document_audit', 'Document upload audit'), ('workflow_throughput', 'Workflow throughput'), ('audit_logs', 'Audit logs')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Saved filter parameters.')),
                ('is_shared', models.BooleanField(default=False, help_text='Visible to other report users in the tenant.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'owner'], name='reports_sav_tenant__1e354b_idx'), models.Index(fields=['tenant', 'report_key'], name='reports_sav_tenant__a8ea5e_idx')],
            },
        ),
    ]
