# Generated by Django 5.1.4 on 2026-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreport',
            name='report_key',
            field=models.CharField(choices=[('employee_list', 'Employee list'), ('headcount_by_department', 'Headcount by department'), ('new_hires', 'New hires'), ('exits', 'Exits'), ('contract_expiry', 'Contract expiry'), ('probation_ending', 'Probation ending'), ('retirement_approaching', 'Retirement approaching'), ('leave_balances', 'Leave balances'), ('leave_taken', 'Leave taken'), ('leave_trends', 'Leave trends'), ('missing_documents', 'Missing required documents'), ('document_audit', 'Document upload audit'), ('attendance_summary', 'Attendance summary'), ('overtime_by_department', 'Overtime by department'), ('workflow_throughput', 'Workflow throughput'), ('audit_logs', 'Audit logs')], max_length=40),
        ),
    ]
