# Generated by Django 5.1.4 on 2026-05-18 20:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=160)),
                ('date_of_birth', models.DateField()),
                ('relationship', models.CharField(choices=[('child', 'Child'), ('stepchild', 'Stepchild'), ('ward', 'Ward'), ('other', 'Other')], default='child', max_length=12)),
                ('education_level', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=12)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('student_number', models.CharField(blank=True, max_length=80)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='dependant-documents/')),
                ('is_benefit_eligible', models.BooleanField(default=True)),
                ('eligibility_override_reason', models.CharField(blank=True, help_text='Audit reason when HR overrides an eligibility flag.', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EducationBenefitRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='Education Assistance Policy', max_length=120)),
                ('max_children', models.PositiveSmallIntegerField(default=2, help_text='Max children per employee eligible for the benefit.')),
                ('covered_levels', models.JSONField(blank=True, default=list, help_text='Education levels covered (empty = all).')),
                ('max_amount_per_child', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum claimable amount per child per period.', max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('frequency', models.CharField(choices=[('term', 'Per term'), ('semester', 'Per semester'), ('year', 'Per year')], default='term', max_length=10)),
                ('eligible_employment_statuses', models.JSONField(blank=True, default=list, help_text='Employment statuses eligible to claim (empty = all).')),
                ('require_probation_passed', models.BooleanField(default=True)),
                ('max_child_age', models.PositiveSmallIntegerField(default=0, help_text='Maximum eligible child age; 0 = no limit.')),
                ('max_claims_per_period', models.PositiveSmallIntegerField(default=1, help_text='Approved claims allowed per employee per period.')),
                ('required_documents', models.JSONField(blank=True, default=list, help_text='ClaimDocumentType values required before submission.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(db_index=True, max_length=40)),
                ('academic_period', models.CharField(help_text="e.g. '2026 Term 1'.", max_length=60)),
                ('period_type', models.CharField(choices=[('term', 'Per term'), ('semester', 'Per semester'), ('year', 'Per year')], default='term', max_length=10)),
                ('education_level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], max_length=12)),
                ('institution_name', models.CharField(max_length=200)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted — pending HR review'), ('more_info', 'More information required'), ('hr_approved', 'HR approved — pending payment'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_note', models.CharField(blank=True, max_length=255)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('payment_reference', models.CharField(blank=True, max_length=80)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='education_assistance.dependant')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_claims', to='employees.employee')),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationClaimApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('hr_review', 'HR review'), ('finance_payment', 'Finance payment')], max_length=16)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('info_requested', 'More information requested'), ('paid', 'Paid')], max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='education_assistance.educationclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationClaimDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice / receipt'), ('proof_of_registration', 'Proof of registration'), ('birth_certificate', 'Birth certificate'), ('proof_of_payment', 'Proof of payment'), ('other', 'Other')], default='other', max_length=24)),
                ('file', models.FileField(upload_to='education-claim-documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='education_assistance.educationclaim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dependant',
            index=models.Index(fields=['tenant', 'employee'], name='education_a_tenant__1f5820_idx'),
        ),
        migrations.AddConstraint(
            model_name='dependant',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'full_name', 'date_of_birth'), name='uniq_dependant_per_employee'),
        ),
        migrations.AddIndex(
            model_name='educationbenefitrule',
            index=models.Index(fields=['tenant', 'is_active'], name='education_a_tenant__df12c5_idx'),
        ),
        migrations.AddIndex(
            model_name='educationclaim',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='education_a_tenant__890d62_idx'),
        ),
        migrations.AddIndex(
            model_name='educationclaim',
            index=models.Index(fields=['tenant', 'status'], name='education_a_tenant__1e84e3_idx'),
        ),
        migrations.AddIndex(
            model_name='educationclaim',
            index=models.Index(fields=['tenant', 'dependant', 'academic_period'], name='education_a_tenant__086e66_idx'),
        ),
        migrations.AddIndex(
            model_name='educationclaimapproval',
            index=models.Index(fields=['tenant', 'claim', 'created_at'], name='education_a_tenant__0b7ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='educationclaimdocument',
            index=models.Index(fields=['tenant', 'claim'], name='education_a_tenant__959867_idx'),
        ),
    ]
