# Generated by Django 5.1.4 on 2026-05-18 18:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('entitled_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('carried_forward_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('taken_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('pending_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Days reserved by requests awaiting approval.', max_digits=7)),
                ('adjustment_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual correction (may be negative).', max_digits=7)),
                ('adjustment_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'leave_type__name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('annual', 'Annual leave'), ('sick', 'Sick leave'), ('maternity', 'Maternity leave'), ('paternity', 'Paternity leave'), ('compassionate', 'Compassionate leave'), ('study', 'Study leave'), ('unpaid', 'Unpaid leave'), ('special', 'Special leave'), ('public_holiday', 'Public holiday'), ('custom', 'Custom leave type')], default='custom', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('colour', models.CharField(default='#2563eb', help_text='Hex colour for calendar display.', max_length=9)),
                ('is_paid', models.BooleanField(default=True)),
                ('default_annual_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Yearly entitlement granted to a new balance.', max_digits=6)),
                ('accrual_method', models.CharField(choices=[('none', 'No accrual — fixed entitlement'), ('annual_lump', 'Full entitlement at start of year'), ('monthly', 'Accrues monthly through the year')], default='annual_lump', max_length=20)),
                ('allow_carry_forward', models.BooleanField(default=False)),
                ('max_carry_forward_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_hr_confirmation', models.BooleanField(default=True, help_text='Adds an HR confirmation stage after the manager.')),
                ('extra_approval_stage', models.BooleanField(default=False, help_text='Adds a final PVC/Admin/Finance approval stage.')),
                ('extra_approval_label', models.CharField(blank=True, help_text='Label for the extra approval stage.', max_length=80)),
                ('notify_finance', models.BooleanField(default=False, help_text='Email the configured Accounts/Finance recipients on approval.')),
                ('requires_documentation', models.BooleanField(default=False, help_text='A supporting document must be attached.')),
                ('min_notice_days', models.PositiveIntegerField(default=0, help_text='Minimum days between application and start date.')),
                ('max_consecutive_days', models.PositiveIntegerField(default=0, help_text='0 = unlimited.')),
                ('allow_negative_balance', models.BooleanField(default=False)),
                ('gender_eligibility', models.CharField(choices=[('any', 'Any'), ('male', 'Male only'), ('female', 'Female only')], default='any', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('start_portion', models.CharField(choices=[('full', 'Full day'), ('first_half', 'First half (morning)'), ('second_half', 'Second half (afternoon)')], default='full', max_length=12)),
                ('end_portion', models.CharField(choices=[('full', 'Full day'), ('first_half', 'First half (morning)'), ('second_half', 'Second half (afternoon)')], default='full', max_length=12)),
                ('total_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Working-day cost of the request (computed).', max_digits=6)),
                ('reason', models.TextField(blank=True)),
                ('contact_during_leave', models.CharField(blank=True, max_length=160)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='leave-documents/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=12)),
                ('current_stage', models.CharField(blank=True, choices=[('manager', 'Line manager approval'), ('hr', 'HR confirmation'), ('extra', 'Additional approval stage')], help_text='Approval stage currently awaiting a decision.', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='leave.leavebalance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('manager', 'Line manager approval'), ('hr', 'HR confirmation'), ('extra', 'Additional approval stage')], max_length=10)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Order within the chain — lower decides first.')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='leave.leaverequest')),
            ],
            options={
                'ordering': ['leave_request', 'sequence'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='leave_leave_tenant__1e482c_idx'), models.Index(fields=['tenant', 'stage', 'status'], name='leave_leave_tenant__e7a127_idx')],
                'constraints': [models.UniqueConstraint(fields=('leave_request', 'sequence'), name='uniq_leaveapproval_sequence_per_request')],
            },
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['tenant', 'is_active'], name='leave_leave_tenant__ce6b74_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_leavetype_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='leave_leave_tenant__88ff5f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['tenant', 'status', 'start_date'], name='leave_leave_tenant__686588_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['tenant', 'leave_type', 'start_date'], name='leave_leave_tenant__f7ec83_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['tenant', 'employee', 'year'], name='leave_leave_tenant__c3bac1_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['tenant', 'leave_type', 'year'], name='leave_leave_tenant__5c0c29_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee', 'leave_type', 'year'), name='uniq_leavebalance_per_employee_type_year'),
        ),
    ]
