# Generated by Django 5.1.4 on 2026-05-19 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('group', models.CharField(blank=True, db_index=True, max_length=60)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('value_type', models.CharField(choices=[('string', 'Text'), ('integer', 'Whole number'), ('boolean', 'True / false'), ('decimal', 'Decimal number'), ('json', 'JSON')], default='string', max_length=10)),
                ('value', models.TextField(blank=True, help_text='Raw value; cast per value_type.')),
                ('is_public', models.BooleanField(default=False, help_text='Readable by any tenant member; otherwise admin-only.')),
                ('is_editable', models.BooleanField(default=True, help_text='A locked setting cannot be changed via the API.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'key'],
                'indexes': [models.Index(fields=['tenant', 'group'], name='system_sett_tenant__e62ba3_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uniq_systemsetting_key_per_tenant')],
            },
        ),
    ]
