/* Client-side download helpers. The "Export" buttons across the app
   pipe live store state through these to produce real CSV / JSON
   files. Documents/payslips/contracts get a tiny PDF-style placeholder
   blob so the download is non-empty. */

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function csvEscape(v: unknown): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

export function rowsToCsv<T extends object>(
  rows: T[],
  columns?: Array<keyof T | { key: keyof T; header: string }>,
): string {
  if (rows.length === 0 && !columns) return "";
  const resolved = columns
    ? columns.map((c) =>
        typeof c === "object" && c !== null
          ? { key: c.key, header: c.header }
          : { key: c as keyof T, header: String(c) },
      )
    : (Object.keys(rows[0]) as Array<keyof T>).map((k) => ({ key: k, header: String(k) }));
  const header = resolved.map((c) => csvEscape(c.header)).join(",");
  const body = rows
    .map((r) => resolved.map((c) => csvEscape((r as Record<string, unknown>)[c.key as string])).join(","))
    .join("\n");
  return `${header}\n${body}`;
}

export function downloadCsv<T extends object>(
  filename: string,
  rows: T[],
  columns?: Array<keyof T | { key: keyof T; header: string }>,
) {
  const csv = rowsToCsv(rows, columns);
  downloadBlob(new Blob([csv], { type: "text/csv;charset=utf-8" }), filename);
}

export function downloadJson(filename: string, data: unknown) {
  downloadBlob(
    new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }),
    filename,
  );
}

/* Minimal valid single-page PDF with a title. Lets "Download payslip"
   and document "Open" actions produce a real file instead of nothing. */
export function generatePlaceholderPdf(title: string, body: string[] = []): Blob {
  const lines = [title, "", ...body, "", "Generated by Bunchly"];
  const stream = lines
    .map((line, i) => `BT /F1 ${i === 0 ? 18 : 11} Tf 50 ${780 - i * 22} Td (${escapePdfText(line)}) Tj ET`)
    .join("\n");
  const content = `q ${stream} Q`;
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((o, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((o) => {
    pdf += `${String(o).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return new Blob([pdf], { type: "application/pdf" });
}

function escapePdfText(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

export function uid(prefix = ""): string {
  return prefix + Math.random().toString(36).slice(2, 8).toUpperCase();
}

export function nowIso(): string {
  return new Date().toISOString();
}

export function todayShort(): string {
  return new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}
